spring.application.name=kjva-bible-api

# 1. Connection Details
# If the variable DATABASE_URL exists, use it. Otherwise, default to local.
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/kjva_bible}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

# 2. Hibernate Strategy (The "Safety Switch")
# 'update' adds new columns but never deletes data. 
# 'validate' is even safer for live production.
spring.jpa.hibernate.ddl-auto=update

# 3. Performance Tuning for Large Bible Imports
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=false

# 4. Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.column_ordering_strategy=com.zioneltechnology.kjva_bible_api.config.CustomColumnOrderingStrategy
spring.jpa.properties.hibernate.column_ordering_strategy=legacy
